In [1]:
import torch

In [26]:
x = torch.FloatTensor([1.5, 1.0])
param = torch.FloatTensor([0.4, 0.5])
w = torch.nn.Parameter(param)

y = sum(w*x)
y_logit = torch.sigmoid(y) # transforming the value to 0~1
print(x, x.size())
print(w, w.size())
print(y)
print(y_logit)
y_logit.backward()
print(w.grad)

tensor([1.5000, 1.0000]) torch.Size([2])
Parameter containing:
tensor([0.4000, 0.5000], requires_grad=True) torch.Size([2])
tensor(1.1000, grad_fn=<AddBackward0>)
tensor(0.7503, grad_fn=<SigmoidBackward>)
tensor([0.2811, 0.1874])
