# Linear Regression

- Linear Data
- Linear Model
- y = 2x+3

## 1. Import Required Libraries

In [21]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable

In [22]:
# visdom is a visualization tool from facebook

from visdom import Visdom
viz = Visdom()

## 2. Generate Data

In [23]:
num_data = 1000 
num_epoch = 1000

noise = init.normal(torch.FloatTensor(num_data,1),std=3)
x = init.uniform(torch.Tensor(num_data,1),-10,10)

y = 2*x+3
y_noise = 2*x+3+noise

print(noise)
print(x)
print(y)
print(y_noise)

tensor([[-1.3999e+00],
        [ 1.6229e+00],
        [-1.8541e+00],
        [ 2.8693e-01],
        [-4.0986e+00],
        [-3.0346e-01],
        [ 2.1523e+00],
        [-1.2357e+00],
        [ 1.4116e-01],
        [ 4.9709e+00],
        [ 2.9456e+00],
        [-1.9646e+00],
        [ 5.1828e+00],
        [-3.2322e+00],
        [-3.0228e+00],
        [ 2.9460e+00],
        [ 1.5971e-01],
        [-4.6314e+00],
        [-4.1380e+00],
        [ 4.7408e+00],
        [ 1.4404e+00],
        [-6.8863e+00],
        [-2.6482e+00],
        [-3.7730e+00],
        [ 3.7044e+00],
        [-2.3460e+00],
        [ 2.6767e+00],
        [-2.8905e+00],
        [ 6.6354e+00],
        [-9.5189e-01],
        [ 3.2897e+00],
        [ 5.2500e-01],
        [ 4.3610e-01],
        [ 1.0030e-01],
        [ 9.1211e-01],
        [ 2.7332e+00],
        [-1.7155e+00],
        [-7.6587e+00],
        [ 6.5073e+00],
        [-1.0294e+00],
        [-5.1213e+00],
        [-1.8456e+00],
        [-6.1886e-01],
        [-1

/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  """


In [24]:
print(noise[0])
print(noise[1])

tensor([-1.3999])
tensor([1.6229])


In [25]:
# visualize data with visdom

input_data = torch.cat([x,y_noise],1)

# build a window with the range of input_data = x, y+noise
win=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=-20,
        ytickmax=20,
        ytickstep=1,
        markersymbol='dot',
        markersize=5,
        markercolor=np.random.randint(0, 255, num_data),
    ),
)

In [33]:
# visualize the linear line
# x, y

viz.line(
    X = x,
    Y = y,
    win=win,
)


'window_372f67c1eceb2e'

### 3. Model & Optimizer

In [27]:
model = nn.Linear(1,1)
output = model(x)

loss_func = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr=0.01)

### 4. Train

In [28]:
# train
loss_arr =[]
label = Variable(y_noise)
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 10 == 0:
        print(loss)
        
    #loss_arr.append(loss.data.numpy()[0])
    loss_arr.append(loss.item())

tensor(145.8038, grad_fn=<MseLossBackward>)
tensor(15.9963, grad_fn=<MseLossBackward>)
tensor(13.7918, grad_fn=<MseLossBackward>)
tensor(12.3200, grad_fn=<MseLossBackward>)
tensor(11.3375, grad_fn=<MseLossBackward>)
tensor(10.6815, grad_fn=<MseLossBackward>)
tensor(10.2436, grad_fn=<MseLossBackward>)
tensor(9.9512, grad_fn=<MseLossBackward>)
tensor(9.7561, grad_fn=<MseLossBackward>)
tensor(9.6258, grad_fn=<MseLossBackward>)
tensor(9.5388, grad_fn=<MseLossBackward>)
tensor(9.4807, grad_fn=<MseLossBackward>)
tensor(9.4419, grad_fn=<MseLossBackward>)
tensor(9.4160, grad_fn=<MseLossBackward>)
tensor(9.3987, grad_fn=<MseLossBackward>)
tensor(9.3872, grad_fn=<MseLossBackward>)
tensor(9.3795, grad_fn=<MseLossBackward>)
tensor(9.3744, grad_fn=<MseLossBackward>)
tensor(9.3709, grad_fn=<MseLossBackward>)
tensor(9.3686, grad_fn=<MseLossBackward>)
tensor(9.3671, grad_fn=<MseLossBackward>)
tensor(9.3661, grad_fn=<MseLossBackward>)
tensor(9.3654, grad_fn=<MseLossBackward>)
tensor(9.3649, grad_fn=<Ms

### 5. Check Trained Parameters

In [29]:
param_list = list(model.parameters())
print(param_list[0].data,param_list[1].data)

tensor([[2.0073]]) tensor([3.0127])


### 6. Visualize output

In [32]:
viz.line(
    X = x,
    Y = output,
    win=win,
)


'window_372f67c1eceb2e'

### 7. Visualize Loss Graph

In [19]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win2=viz.line(
    X = x,
    Y = loss_data,
)