# Linear Regression

- Linear Data
- Linear Model
- y = 2x+3

## 1. Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable

In [2]:
# visdom is a visualization tool from facebook

from visdom import Visdom
viz = Visdom()

## 2. Generate Data

In [15]:
num_data = 1000 
num_epoch = 1000

noise = init.normal(torch.FloatTensor(num_data,1),std=3)
x = init.uniform(torch.Tensor(num_data,1),-10,10)

y = 2*x+3
y_noise = 2*x+3+noise

print(noise)
print(x)
print(y)
print(y_noise)

tensor([[-1.9715e+00],
        [ 2.4148e+00],
        [ 1.0911e+00],
        [-6.2556e+00],
        [ 1.9909e+00],
        [ 5.4137e+00],
        [-3.6600e+00],
        [ 4.0644e-02],
        [-6.3828e-01],
        [ 1.1953e+00],
        [ 7.0110e-01],
        [-7.6474e+00],
        [-3.7344e+00],
        [-6.8550e-02],
        [-1.7196e-01],
        [ 1.3176e+00],
        [ 1.2127e+00],
        [-4.5592e+00],
        [ 3.1535e+00],
        [-5.2415e+00],
        [ 5.6309e+00],
        [-4.4394e+00],
        [-3.1229e+00],
        [-1.7499e+00],
        [ 3.4227e+00],
        [-5.2828e+00],
        [-2.4950e+00],
        [-2.1027e+00],
        [-1.0738e-01],
        [-9.6904e-01],
        [ 2.7245e+00],
        [ 3.2913e+00],
        [ 1.7943e+00],
        [ 7.1257e-02],
        [-2.7066e+00],
        [ 9.0139e+00],
        [-4.1600e+00],
        [ 2.1960e+00],
        [ 3.9740e+00],
        [ 1.2559e-01],
        [-5.7788e-01],
        [ 2.1876e-01],
        [ 5.0935e+00],
        [-4

/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  """


In [5]:
print(noise[0])
print(noise[1])

tensor([0.8730])
tensor([1.4967])


In [16]:
# visualize data with visdom

input_data = torch.cat([x,y_noise],1)

# build a window with the range of input_data = x, y+noise
win=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=-20,
        ytickmax=20,
        ytickstep=1,
        markersymbol='dot',
        markersize=5,
        markercolor=np.random.randint(0, 255, num_data),
    ),
)

'\nviz.line(\n    X = x,\n    Y = y,\n    win=win,\n)\n'

In [17]:
# visualize the linear line
# x, y

viz.line(
    X = x,
    Y = y,
    win=win,
)


'window_372e77631c984e'

### 3. Model & Optimizer

In [7]:
model = nn.Linear(1,1)
output = model(x)

loss_func = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr=0.01)

### 4. Train

In [8]:
# train
loss_arr =[]
label = Variable(y_noise)
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 10 == 0:
        print(loss)
        
    #loss_arr.append(loss.data.numpy()[0])
    loss_arr.append(loss.item())

tensor(61.3697, grad_fn=<MseLossBackward>)
tensor(10.5452, grad_fn=<MseLossBackward>)
tensor(7.3592, grad_fn=<MseLossBackward>)
tensor(5.2309, grad_fn=<MseLossBackward>)
tensor(3.8092, grad_fn=<MseLossBackward>)
tensor(2.8596, grad_fn=<MseLossBackward>)
tensor(2.2252, grad_fn=<MseLossBackward>)
tensor(1.8014, grad_fn=<MseLossBackward>)
tensor(1.5183, grad_fn=<MseLossBackward>)
tensor(1.3292, grad_fn=<MseLossBackward>)
tensor(1.2029, grad_fn=<MseLossBackward>)
tensor(1.1186, grad_fn=<MseLossBackward>)
tensor(1.0622, grad_fn=<MseLossBackward>)
tensor(1.0245, grad_fn=<MseLossBackward>)
tensor(0.9994, grad_fn=<MseLossBackward>)
tensor(0.9826, grad_fn=<MseLossBackward>)
tensor(0.9714, grad_fn=<MseLossBackward>)
tensor(0.9639, grad_fn=<MseLossBackward>)
tensor(0.9589, grad_fn=<MseLossBackward>)
tensor(0.9555, grad_fn=<MseLossBackward>)
tensor(0.9533, grad_fn=<MseLossBackward>)
tensor(0.9518, grad_fn=<MseLossBackward>)
tensor(0.9508, grad_fn=<MseLossBackward>)
tensor(0.9501, grad_fn=<MseLossB

### 5. Check Trained Parameters

In [9]:
param_list = list(model.parameters())
print(param_list[0].data,param_list[1].data)

tensor([[1.9898]]) tensor([2.9436])


### 6. Visualize output

In [10]:
win_2=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=-20,
        ytickmax=20,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)

viz.line(
    X = x,
    Y = output.data,
    win = win_2,
    opts=dict(
        xtickmin=-15,
        xtickmax=10,
        xtickstep=1,
        ytickmin=-300,
        ytickmax=200,
        ytickstep=1,
        markersymbol='dot',
    ),
)

'window_372e746078055c'

### 7. Visualize Loss Graph

In [11]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win2=viz.line(
    X = x,
    Y = loss_data,
)