# Neural Network with Quadratic Data
출처: https://github.com/GunhoChoi/PyTorch-FastCampus/blob/master/02_Regression%26NN/1_NN_code/1d_data/0_neural_quadratic.ipynb
- y = 8x^2+7x+3
- 4 hidden layers

<img src="./quadratic.png">

사진출처: http://cs.franklin.edu/~sieberth/MATH160/bookFiles/Chapter3/333371_0307_317-323.pdf 

## 1.Import Required Libraries

In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
from visdom import Visdom
viz = Visdom()

## 2. Data Generation

In [3]:
num_data = 1000
num_epoch = 5000

noise = init.normal(torch.FloatTensor(num_data,1),std=3)

x = init.uniform(torch.Tensor(num_data,1),-15,15)
y = (x**2) + 3 

y_noise = y + noise

/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  


In [4]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-15,
        xtickmax=15,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


In [5]:

win=viz.scatter(
    X = torch.cat([x,y],1),
    opts=dict(
        xtickmin=-15,
        xtickmax=15,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


## 3. Model & Optimizer

In [6]:
# fully connected model with 4 hidden layer

model = nn.Sequential(
        nn.Linear(1,6),
        nn.ReLU(),
        nn.Linear(6,1)
    )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

## 4. Train 

In [7]:
loss_arr =[]
label = y_noise

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)

    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 100 ==0:
        print(loss)
    
    #loss_arr.append(loss.cpu().data.numpy()[0])
    loss_arr.append(loss.item())

tensor(80.8873, grad_fn=<L1LossBackward>)
tensor(75.1028, grad_fn=<L1LossBackward>)
tensor(66.6297, grad_fn=<L1LossBackward>)
tensor(53.1860, grad_fn=<L1LossBackward>)
tensor(39.7944, grad_fn=<L1LossBackward>)
tensor(29.8248, grad_fn=<L1LossBackward>)
tensor(23.4841, grad_fn=<L1LossBackward>)
tensor(21.8903, grad_fn=<L1LossBackward>)
tensor(21.6660, grad_fn=<L1LossBackward>)
tensor(21.5617, grad_fn=<L1LossBackward>)
tensor(21.4644, grad_fn=<L1LossBackward>)
tensor(21.3698, grad_fn=<L1LossBackward>)
tensor(21.2784, grad_fn=<L1LossBackward>)
tensor(21.1902, grad_fn=<L1LossBackward>)
tensor(21.1031, grad_fn=<L1LossBackward>)
tensor(21.0179, grad_fn=<L1LossBackward>)
tensor(20.9351, grad_fn=<L1LossBackward>)
tensor(20.8537, grad_fn=<L1LossBackward>)
tensor(20.7724, grad_fn=<L1LossBackward>)
tensor(20.6913, grad_fn=<L1LossBackward>)
tensor(20.6118, grad_fn=<L1LossBackward>)
tensor(20.5341, grad_fn=<L1LossBackward>)
tensor(20.4580, grad_fn=<L1LossBackward>)
tensor(20.3830, grad_fn=<L1LossBac

In [8]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[-0.3473],
        [ 2.3066],
        [ 2.1561],
        [ 1.2727],
        [ 0.8066],
        [-3.3050]], requires_grad=True), Parameter containing:
tensor([ 0.5517, -0.6659, -0.8198, -0.9582, -0.3850, -1.7393],
       requires_grad=True), Parameter containing:
tensor([[-0.0740,  2.1022,  2.0552,  1.4345,  0.6932,  3.6068]],
       requires_grad=True), Parameter containing:
tensor([-1.3463], requires_grad=True)]


## 5. Visualize Trained Output

In [9]:
win2=viz.scatter(
    X = torch.cat([x, output],1),
    opts=dict(
        xtickmin=-15,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


## 6. Visualize Loss Graph

In [10]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win3=viz.line(
    X = x,
    Y = loss_data,
)