# Neural Network with Quadratic Data
출처: https://github.com/GunhoChoi/PyTorch-FastCampus/blob/master/02_Regression%26NN/1_NN_code/1d_data/0_neural_quadratic.ipynb
- y = 8x^2+7x+3
- 4 hidden layers

<img src="./quadratic.png">

사진출처: http://cs.franklin.edu/~sieberth/MATH160/bookFiles/Chapter3/333371_0307_317-323.pdf 

## 1.Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
from visdom import Visdom
viz = Visdom()

## 2. Data Generation

In [2]:
num_data = 1000
num_epoch = 5000

noise = init.normal(torch.FloatTensor(num_data,1),std=3)

x = init.uniform(torch.Tensor(num_data,1),-15,15)
y = (x**2) + 3 

y_noise = y + noise

/Users/lim/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/Users/lim/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  


In [3]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-15,
        xtickmax=15,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


In [4]:

win=viz.scatter(
    X = torch.cat([x,y],1),
    opts=dict(
        xtickmin=-15,
        xtickmax=15,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


## 3. Model & Optimizer

In [5]:
# fully connected model with 4 hidden layer

model = nn.Sequential(
        nn.Linear(1,6),
        nn.ReLU(),
        nn.Linear(6,1)
    )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

## 4. Train 

In [6]:
loss_arr =[]
label = y_noise

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)

    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 100 ==0:
        print(loss)
    
    #loss_arr.append(loss.cpu().data.numpy()[0])
    loss_arr.append(loss.item())

tensor(77.8420, grad_fn=<L1LossBackward>)
tensor(73.6337, grad_fn=<L1LossBackward>)
tensor(67.0424, grad_fn=<L1LossBackward>)
tensor(54.6285, grad_fn=<L1LossBackward>)
tensor(36.6794, grad_fn=<L1LossBackward>)
tensor(24.5534, grad_fn=<L1LossBackward>)
tensor(21.4724, grad_fn=<L1LossBackward>)
tensor(21.1204, grad_fn=<L1LossBackward>)
tensor(21.0160, grad_fn=<L1LossBackward>)
tensor(20.9263, grad_fn=<L1LossBackward>)
tensor(20.8380, grad_fn=<L1LossBackward>)
tensor(20.7510, grad_fn=<L1LossBackward>)
tensor(20.6634, grad_fn=<L1LossBackward>)
tensor(20.5771, grad_fn=<L1LossBackward>)
tensor(20.4926, grad_fn=<L1LossBackward>)
tensor(20.4084, grad_fn=<L1LossBackward>)
tensor(20.3251, grad_fn=<L1LossBackward>)
tensor(20.2441, grad_fn=<L1LossBackward>)
tensor(20.1631, grad_fn=<L1LossBackward>)
tensor(20.0819, grad_fn=<L1LossBackward>)
tensor(20.0007, grad_fn=<L1LossBackward>)
tensor(19.9186, grad_fn=<L1LossBackward>)
tensor(19.8360, grad_fn=<L1LossBackward>)
tensor(19.7536, grad_fn=<L1LossBac

In [7]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[-0.0102],
        [ 0.1442],
        [-1.5690],
        [-2.6876],
        [ 3.2678],
        [-0.0409]], requires_grad=True), Parameter containing:
tensor([-0.1519,  0.0036, -1.8442, -2.0025, -1.6943, -0.6115],
       requires_grad=True), Parameter containing:
tensor([[-0.0830,  0.0780,  2.1766,  3.2546,  3.5368, -0.3724]],
       requires_grad=True), Parameter containing:
tensor([-0.8754], requires_grad=True)]


## 5. Visualize Trained Output

In [8]:
win2=viz.scatter(
    X = torch.cat([x, output],1),
    opts=dict(
        xtickmin=-15,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


## 6. Visualize Loss Graph

In [9]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win3=viz.line(
    X = x,
    Y = loss_data,
)