# Neural Network with Quadratic Data
출처: https://github.com/GunhoChoi/PyTorch-FastCampus/blob/master/02_Regression%26NN/1_NN_code/1d_data/0_neural_quadratic.ipynb
- y = 8x^2+7x+3
- 4 hidden layers

<img src="./quadratic.png">

사진출처: http://cs.franklin.edu/~sieberth/MATH160/bookFiles/Chapter3/333371_0307_317-323.pdf 

## 1.Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

from torch.autograd import Variable
from visdom import Visdom
viz = Visdom()

## 2. Data Generation

In [2]:
num_data = 1000
num_epoch = 5000

noise = init.normal(torch.FloatTensor(num_data,1),std=3)

x = init.uniform(torch.Tensor(num_data,1),-15,15)
y = (x**2) + 3 

y_noise = y + noise

/Users/lim/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/Users/lim/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  


In [3]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-15,
        xtickmax=15,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


In [4]:

win=viz.scatter(
    X = torch.cat([x,y],1),
    opts=dict(
        xtickmin=-15,
        xtickmax=15,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


## 문제1. Layer가 4개인 Neural모델을 생성해 봅시다.
 - layer1은 W가 6개 + ReLU
 - layer2는 W가 4개 + ReLU
 - layer3은 W가 7개 + ReLU
 - 힌트: 마지막에 반환될 값은 한개가 되겠죠?

## 3. Model & Optimizer

In [5]:
# 3. Build the Model as a Class

#model = nn.Sequential(
#        nn.Linear(input_size, hidden_size),
#        nn.ReLU(),
#        nn.Linear(6,1)
#    )

class MyModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MyModel, self).__init__()

        self.linear1 = ## 코드를 작성해 보세요!! 힌트: W의 갯수가 몇개죠?
        self.relu = ##  코드를 작성해 보세요!!
        self.linear2 = ## 코드를 작성해 보세요!! 힌트: 몇개의 데이터가 최종적으로 반환되어야 할까요?
        
    def forward(self, x):
        
        y = self.linear1(x)
        y_relu = self.relu(y)
        z = self.linear2(y_relu)
        
        return z

model = MyModel(1,12,1)

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

In [6]:
'''
model = nn.Sequential(

    ## 여기에 코드를 넣으세요.
    
    )
'''

'\nmodel = nn.Sequential(\n\n    ## 여기에 코드를 넣으세요.\n    \n    )\n'

## 4. Train 

In [7]:
loss_arr =[]
label = y_noise

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model.forward(x)

    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 100 ==0:
        print(loss)
    
    #loss_arr.append(loss.cpu().data.numpy()[0])
    loss_arr.append(loss.item())

tensor(71.9169, grad_fn=<L1LossBackward>)
tensor(63.4106, grad_fn=<L1LossBackward>)
tensor(48.5161, grad_fn=<L1LossBackward>)
tensor(29.9668, grad_fn=<L1LossBackward>)
tensor(21.5439, grad_fn=<L1LossBackward>)
tensor(19.9107, grad_fn=<L1LossBackward>)
tensor(19.7616, grad_fn=<L1LossBackward>)
tensor(19.6753, grad_fn=<L1LossBackward>)
tensor(19.5890, grad_fn=<L1LossBackward>)
tensor(19.5024, grad_fn=<L1LossBackward>)
tensor(19.4154, grad_fn=<L1LossBackward>)
tensor(19.3277, grad_fn=<L1LossBackward>)
tensor(19.2403, grad_fn=<L1LossBackward>)
tensor(19.1527, grad_fn=<L1LossBackward>)
tensor(19.0647, grad_fn=<L1LossBackward>)
tensor(18.9774, grad_fn=<L1LossBackward>)
tensor(18.8901, grad_fn=<L1LossBackward>)
tensor(18.8012, grad_fn=<L1LossBackward>)
tensor(18.7108, grad_fn=<L1LossBackward>)
tensor(18.6196, grad_fn=<L1LossBackward>)
tensor(18.5282, grad_fn=<L1LossBackward>)
tensor(18.4366, grad_fn=<L1LossBackward>)
tensor(18.3454, grad_fn=<L1LossBackward>)
tensor(18.2542, grad_fn=<L1LossBac

In [8]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[ 1.3504],
        [ 1.5298],
        [-1.6294],
        [-0.2808],
        [-1.2541],
        [-2.0132],
        [ 1.3296],
        [-0.0383],
        [-0.0222],
        [ 1.3129],
        [-1.2934],
        [ 0.9781]], requires_grad=True), Parameter containing:
tensor([-1.7627, -2.1130, -1.1877, -0.4254, -1.9531, -1.4748, -1.0591, -0.5737,
         0.3324, -1.3580, -0.8094, -1.9781], requires_grad=True), Parameter containing:
tensor([[ 1.9847,  2.3012,  1.8930,  0.4382,  2.1563,  2.3231,  1.5672, -0.2395,
         -0.2232,  1.6593,  1.4489,  1.9874]], requires_grad=True), Parameter containing:
tensor([-1.4168], requires_grad=True)]


## 5. Visualize Trained Output

In [9]:
win2=viz.scatter(
    X = torch.cat([x, output],1),
    opts=dict(
        xtickmin=-15,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


## 6. Visualize Loss Graph

In [10]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win3=viz.line(
    X = x,
    Y = loss_data,
)