# Neural Network with Cubic Data (multi-dimensional)
- y = x^3 -3x^2 -9x -1
- 5 hidden layers

## 1.Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
from visdom import Visdom
viz = Visdom()

## 2. Data Generation

In [5]:
num_data = 1000
num_epoch = 5000

x = init.uniform(torch.Tensor(num_data,1),-10,10)
y = (x**3) - 3*(x**2) - 9*x - 1

noise = init.normal(torch.FloatTensor(num_data,1),std=3)

y_noise = y + noise

/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  after removing the cwd from sys.path.
/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  import sys


In [6]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)

In [7]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = torch.cat([x,y],1),
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)

## 3. Model & Optimizer

In [8]:
# fully connected model with 5 hidden layer

model = nn.Sequential(
            nn.Linear(1,20),
            nn.ReLU(),
            nn.Linear(20,10),
            nn.ReLU(),
            nn.Linear(10,5),
            nn.ReLU(),
            nn.Linear(5,1),
        )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.0005)

## 4. Train 

In [10]:
loss_arr =[]
label = y_noise

for i in range(num_epoch):
    output = model(x)
    optimizer.zero_grad()

    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 100 ==0:
        print(loss)
        
    #loss_arr.append(loss.cpu().data.numpy()[0])
    loss_arr.append(loss.item())

tensor(204.4301, grad_fn=<L1LossBackward>)
tensor(204.3575, grad_fn=<L1LossBackward>)
tensor(204.2652, grad_fn=<L1LossBackward>)
tensor(204.1372, grad_fn=<L1LossBackward>)
tensor(203.9411, grad_fn=<L1LossBackward>)
tensor(203.6156, grad_fn=<L1LossBackward>)
tensor(203.0410, grad_fn=<L1LossBackward>)
tensor(201.9357, grad_fn=<L1LossBackward>)
tensor(199.3703, grad_fn=<L1LossBackward>)
tensor(191.3913, grad_fn=<L1LossBackward>)
tensor(160.1453, grad_fn=<L1LossBackward>)
tensor(134.2509, grad_fn=<L1LossBackward>)
tensor(133.2757, grad_fn=<L1LossBackward>)
tensor(132.3921, grad_fn=<L1LossBackward>)
tensor(131.4680, grad_fn=<L1LossBackward>)
tensor(130.4908, grad_fn=<L1LossBackward>)
tensor(129.4394, grad_fn=<L1LossBackward>)
tensor(128.2592, grad_fn=<L1LossBackward>)
tensor(126.9604, grad_fn=<L1LossBackward>)
tensor(125.4518, grad_fn=<L1LossBackward>)
tensor(123.6775, grad_fn=<L1LossBackward>)
tensor(121.5244, grad_fn=<L1LossBackward>)
tensor(118.7848, grad_fn=<L1LossBackward>)
tensor(115.

In [11]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[ 0.7475],
        [-0.4363],
        [-0.2682],
        [-0.5952],
        [-0.6621],
        [ 0.6841],
        [-0.4795],
        [-0.6447],
        [ 1.0006],
        [ 0.4622],
        [ 0.4706],
        [-0.5996],
        [-0.5254],
        [ 1.5467],
        [-0.4452],
        [ 0.2992],
        [ 0.0456],
        [ 0.2445],
        [ 0.5043],
        [-0.9219]], requires_grad=True), Parameter containing:
tensor([-3.4015, -2.8000, -1.3406, -2.6527, -1.2210,  0.9777, -1.6541, -3.7057,
         0.9133,  0.6792, -2.6207, -1.2887,  0.5238,  0.7543, -1.9942,  0.1557,
        -0.6209, -0.7606, -1.0957, -1.6237], requires_grad=True), Parameter containing:
tensor([[ 0.2295, -0.1259, -0.1149, -0.1376, -0.1407, -0.0087,  0.2154,  0.1190,
          0.0798,  0.1097, -0.1709,  0.0085, -0.2210, -0.0897, -0.1071, -0.1565,
         -0.0376, -0.0334,  0.0526,  0.2063],
        [ 0.1049,  1.0123,  0.5155,  0.6560,  0.3726, -0.0309,  0.2900,  1.2921,
         -0.1179

## 5. Visualize Trained Output

In [14]:
win2=viz.scatter(
    X = torch.cat([x, output],1),
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)


## 6. Visualize Loss Graph

In [15]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win3=viz.line(
    X = x,
    Y = loss_data, 
)