# Neural Network with Cubic Data (multi-dimensional)
- y = x^3 -3x^2 -9x -1
- 5 hidden layers

## 1.Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
from visdom import Visdom
viz = Visdom()

## 2. Data Generation

In [2]:
num_data = 1000
num_epoch = 5000

x = init.uniform(torch.Tensor(num_data,1),-10,10)
y = (x**3) - 3*(x**2) - 9*x - 1

noise = init.normal(torch.FloatTensor(num_data,1),std=3)

y_noise = y + noise

/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  after removing the cwd from sys.path.
/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  import sys


In [3]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)

In [4]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = torch.cat([x,y],1),
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)

## 3. Model & Optimizer

In [5]:
# fully connected model with 5 hidden layer

model = nn.Sequential(
            nn.Linear(1,20),
            nn.ReLU(),
            nn.Linear(20,10),
            nn.ReLU(),
            nn.Linear(10,5),
            nn.ReLU(),
            nn.Linear(5,1),
        )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

## 4. Train 

In [6]:
loss_arr =[]
label = y_noise

for i in range(num_epoch):
    output = model(x)
    optimizer.zero_grad()

    loss = loss_func(output,label)
    loss.backward()
    
    optimizer.step()
    
    if i % 100 ==0:
        print(loss)
        
    #loss_arr.append(loss.cpu().data.numpy()[0])
    loss_arr.append(loss.item())

tensor(210.9340, grad_fn=<L1LossBackward>)
tensor(210.8821, grad_fn=<L1LossBackward>)
tensor(210.8308, grad_fn=<L1LossBackward>)
tensor(210.8036, grad_fn=<L1LossBackward>)
tensor(210.7703, grad_fn=<L1LossBackward>)
tensor(210.7277, grad_fn=<L1LossBackward>)
tensor(210.6704, grad_fn=<L1LossBackward>)
tensor(210.5876, grad_fn=<L1LossBackward>)
tensor(210.4600, grad_fn=<L1LossBackward>)
tensor(210.2420, grad_fn=<L1LossBackward>)
tensor(209.8103, grad_fn=<L1LossBackward>)
tensor(208.7260, grad_fn=<L1LossBackward>)
tensor(204.5924, grad_fn=<L1LossBackward>)
tensor(166.6677, grad_fn=<L1LossBackward>)
tensor(133.7842, grad_fn=<L1LossBackward>)
tensor(129.7256, grad_fn=<L1LossBackward>)
tensor(123.7340, grad_fn=<L1LossBackward>)
tensor(115.6698, grad_fn=<L1LossBackward>)
tensor(108.3235, grad_fn=<L1LossBackward>)
tensor(99.2278, grad_fn=<L1LossBackward>)
tensor(84.6065, grad_fn=<L1LossBackward>)
tensor(64.0752, grad_fn=<L1LossBackward>)
tensor(58.7412, grad_fn=<L1LossBackward>)
tensor(54.6009,

In [7]:
param_list = list(model.parameters())
print(param_list)



[Parameter containing:
tensor([[ 0.5488],
        [-0.9242],
        [-0.5968],
        [ 0.7953],
        [ 0.6045],
        [-0.2598],
        [-0.5008],
        [-0.6928],
        [ 0.4209],
        [-0.1503],
        [-0.5346],
        [-1.4426],
        [ 0.6893],
        [-0.4991],
        [ 0.4590],
        [ 0.3660],
        [-0.6303],
        [-0.0624],
        [ 0.4534],
        [ 0.4127]], requires_grad=True), Parameter containing:
tensor([-3.5839, -3.7680, -3.2380, -2.6092, -4.2364, -1.0848, -3.2996, -4.6267,
         0.1931,  0.5922, -2.2915, -2.4222, -3.7517, -2.8975, -1.9973,  0.4620,
        -2.8584, -0.6654, -0.3538,  0.2815], requires_grad=True), Parameter containing:
tensor([[-1.1666e-01,  1.9279e-02,  8.0801e-02,  1.9196e-01, -9.7504e-02,
          2.1056e-01,  2.1495e-02, -1.2273e-01, -1.0769e-01,  1.1352e-01,
          9.5345e-02, -1.6672e-01,  1.5637e-01, -1.3247e-01,  7.6810e-02,
          1.9413e-01, -3.1924e-02,  1.2949e-01, -2.1333e-01, -1.7133e-01],
        

## 5. Visualize Trained Output

In [8]:
win2=viz.scatter(
    X = torch.cat([x, output],1),
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)



## 6. Visualize Loss Graph

In [9]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win3=viz.line(
    X = x,
    Y = loss_data, 
)