# Neural Network with 2D Data (2-dimensional)
- Neural Network with 4 layers
- 2D data f(x,y) -> R

## 1.Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
from visdom import Visdom
viz = Visdom()

## 2. Data Generation

In [2]:
num_data=1000
num_epoch=10000

x = init.uniform(torch.Tensor(num_data,1),-10,10)
y = init.uniform(torch.Tensor(num_data,1),-10,10)
z = x**2 + y**2

x_noise = x + init.normal(torch.FloatTensor(num_data,1),std=0.5)
y_noise = y + init.normal(torch.FloatTensor(num_data,1),std=0.5)
z_noise = x_noise**2 + y_noise**2

data_noise = torch.cat([x,y,z_noise],1)

/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  after removing the cwd from sys.path.
/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  """
/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:8: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  
/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:9: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  if __name__ == '__main__':


In [3]:
# data visualization

win_1=viz.scatter(
        X=data_noise,
        opts=dict(
            markersize=5,
            markercolor=np.ndarray(shape=[num_data,3],dtype=float,buffer=[51,153,255]*np.ones(shape=[num_data,3]))
            )
        )

## 3. Model & Optimizer

In [4]:
model = nn.Sequential(
            nn.Linear(2,20),
            nn.ReLU(),
            nn.Linear(20,10),
            nn.ReLU(),
            nn.Linear(10,5),
            nn.ReLU(),
            nn.Linear(5,5),
            nn.ReLU(),
            nn.Linear(5,1),
        )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

## 4. Train 

In [5]:
input_data = torch.cat([x,y],1)
label = z_noise
loss_arr =[]

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(input_data)
    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    loss_arr.append(loss.item())
    
    if i % 100 == 0 and i <1000:
        print(loss)
        data = torch.cat([input_data.cpu(),output.cpu().data],1)

        win_2 =viz.scatter(
                X=data,
                opts=dict(
                markersize=5,
                markercolor=np.ndarray(shape=[num_data,3],dtype=float,buffer=128*np.ones(shape=[num_data,3]))
            )
    )

tensor(65.7104, grad_fn=<L1LossBackward>)
tensor(65.2817, grad_fn=<L1LossBackward>)
tensor(64.3548, grad_fn=<L1LossBackward>)
tensor(59.0717, grad_fn=<L1LossBackward>)
tensor(17.8562, grad_fn=<L1LossBackward>)
tensor(16.8119, grad_fn=<L1LossBackward>)
tensor(15.9797, grad_fn=<L1LossBackward>)
tensor(15.1852, grad_fn=<L1LossBackward>)
tensor(14.3976, grad_fn=<L1LossBackward>)
tensor(13.5923, grad_fn=<L1LossBackward>)


In [6]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[ 0.6850, -0.0502],
        [-0.0602,  0.6183],
        [-0.5313, -0.1488],
        [ 0.2152, -0.4306],
        [-0.3224,  0.5263],
        [-0.5309, -0.2665],
        [-0.0100,  0.5336],
        [-0.5840,  0.3759],
        [ 0.0469, -0.3801],
        [ 0.1406, -0.0129],
        [ 0.5754,  0.1552],
        [-0.6669, -0.1991],
        [ 0.3849,  0.2107],
        [ 0.2044, -0.2215],
        [ 0.6126, -0.4046],
        [-0.1895,  0.0895],
        [ 0.0031, -0.6413],
        [ 0.5738,  0.2672],
        [ 0.0506, -0.3940],
        [-0.3437, -0.5539]], requires_grad=True), Parameter containing:
tensor([-0.4888, -1.0308,  0.7251, -0.5987, -0.5087, -0.9675, -0.1662, -0.4251,
        -0.1087,  0.0203, -0.1181,  0.3905, -0.9619,  0.9565, -0.4687, -1.1564,
        -1.0662,  0.4190,  0.1819, -0.4831], requires_grad=True), Parameter containing:
tensor([[ 1.4889e-01, -1.1155e-01, -1.6971e-01, -8.6068e-02, -1.5838e-02,
         -2.3946e-02,  1.7094e-01, -8.2129e-02,  7.

## 5. Visualize Trained Output

In [7]:
data = torch.cat([input_data.cpu(),output.cpu().data],1)

win_2 =viz.scatter(
        X=data,
        opts=dict(
        markersize=5,
        markercolor=np.ndarray(shape=[num_data,3],dtype=float,buffer=128*np.ones(shape=[num_data,3]))
    )
)

## 6. Visualize Loss Graph

In [8]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win3=viz.line(
    X = x,
    Y = loss_data,
)